### ISSUE TITLE
Tik tok?

### ISSUE THREAD

**Issue by japanesename** [machadop1407/Whatsapp-Bot#1]
In your readme you said that the bot sends a message to a tik tok user but the title and github is named `Whatsapp bot`, Is it supposed to be like that?

**Comment by machadop1407** [comment]
Hey, really sorry about that! I have no idea why I wrote tik tok at the
time, just changed it!

**Comment by japanesename** [comment]
Ah i see.. Thanks im gonna close this issue now :)
