### ISSUE TITLE
TimeoutError: waiting for selector `._1MXsz` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by Sakthisaba** [machadop1407/Whatsapp-Bot#4]
Update selector name to get rid of this issue

**Comment by Shubh0075** [comment]
what should be the new selector name?

**Comment by Sakthisaba** [comment]
Update below selector names in your code

          Old                                    New
      ._1MXsz                    ->            ._3hKpJ
      ._3uMse                    ->           ._1LbR4
       div[data-tab='1']         ->       div[data-tab='10']
